=== 2lambda123/starjava/table/src/docs/docs.dtd
<!ENTITY % paracontent "( #PCDATA
                            | em | strong | code
                            | webref | javadoc | ref
                            | blockquote | verbatim | dl | ul | ol
                           )*">

  <!ELEMENT sun ( docinfo?, docbody )>
  <!ELEMENT docinfo ( title?, 
                      authorlist?,
                      softwareversion?,
                      docnumber?,
                      docdate?,
                      contactlist? )>
  <!ELEMENT title ( #PCDATA )>
  <!ELEMENT authorlist ( author* )>
  <!ELEMENT author ( #PCDATA )>
  <!ELEMENT softwareversion ( #PCDATA )>
  <!ELEMENT docnumber ( #PCDATA )>
  <!ELEMENT docdate ( #PCDATA )>
  <!ELEMENT contactlist ( contact* )>
  <!ELEMENT contact %paracontent;>
  <!ELEMENT docbody ( abstract?, sect* )>
  <!ELEMENT abstract ( px* )>
  <!ELEMENT subhead ( title )>
  <!ELEMENT p %paracontent;>
  <!ELEMENT px %paracontent;>
  <!ELEMENT ul ( li* )>
  <!ELEMENT ol ( li* )>
  <!ELEMENT li %paracontent;>
  <!ELEMENT dl ( ( dt, dd? )* )>
  <!ELEMENT dt %paracontent;>
  <!ELEMENT dd ( p* )>
  <!ELEMENT em %paracontent;>
  <!ELEMENT strong %paracontent;>
  <!ELEMENT code %paracontent;>
  <!ELEMENT verbatim ( #PCDATA )>
  <!ELEMENT blockquote %paracontent;>

  <!ELEMENT ref ( #PCDATA )>
  <!ATTLIST ref id IDREF #REQUIRED
                hypertext CDATA #IMPLIED
                plaintext CDATA #IMPLIED>

  <!ELEMENT webref ( #PCDATA )>
  <!ATTLIST webref url CDATA #REQUIRED
                   hypertext CDATA #IMPLIED
                   plaintext CDATA #IMPLIED>

  <!ELEMENT javadoc ( #PCDATA )>
  <!ATTLIST javadoc class CDATA #REQUIRED
                    member CDATA #IMPLIED
                    docset CDATA #IMPLIED
                    hypertext CDATA #IMPLIED 
                    plaintext CDATA #IMPLIED>

  <!ELEMENT sect ( subhead?, ( p | subsect )* )>
  <!ATTLIST sect id ID #IMPLIED>

  <!ELEMENT subsect ( subhead?, ( p | subsubsect )* )*>
  <!ATTLIST subsect id ID #IMPLIED>

  <!ELEMENT subsubsect ( subhead?, p* )*>
  <!ATTLIST subsubsect id ID #IMPLIED>

=== 2lambda123/starjava/table/src/docs/sun252.xml
<?xml version='1.0'?>
<!DOCTYPE sun SYSTEM "docs.dtd" [
  <!ENTITY coredocs "http://java.sun.com/j2se/1.4/docs/api/">
  <!ENTITY nbsp     "&#xA0;">
]>

<sun>

<docinfo>

<title>STIL - Starlink Tables Infrastructure Library</title>

<authorlist>
<author>Mark Taylor</author>
</authorlist>

<docnumber>252</docnumber>

<docdate>22 January 2004</docdate>

<contactlist>
<contact>STIL web page:
         <webref url="http://www.star.bris.ac.uk/~mbt/stil/"/></contact>
<contact>Author email:
         <webref url="mailto:m.b.taylor@bristol.ac.uk"
                 >m.b.taylor@bristol.ac.uk</webref></contact>
<contact>Starlink: <webref url="http://www.starlink.ac.uk/"/></contact>
</contactlist>

</docinfo>

<!-- .......................................................... -->
<docbody>
<abstract>

<px>STIL is a set of Java class libraries which allow input,
manipulation and output of tabular data.
As well as an abstract and format-independent definition of what 
constitutes a table, and an extensible framework for "pull-model"
table processing, it provides a number of format-specific
handlers which know how to serialize/deserialize tables; 
amongst others handlers are provided for the VOTable and FITS formats.
The framework for interaction between the core table manipulation
facilities and the format-specific handlers is open and pluggable,
so that handlers for new formats can easily be added.
</px>

<px>The VOTable handling in particular is provided by a high quality 
library which performs efficient XML parsing and can read and 
write VOTables in any of the defined formats (TABLEDATA, BINARY or FITS).
It may be used on its own for VOTable I/O without much reference to
the format-independent parts of the library.
</px>

</abstract>

<sect>
<subhead><title>Introduction</title></subhead>

<p>STIL is a set of class libraries which can do input, output
and manipulation of tables.  It has been developed for use with
astronomical tables, though it could be used for any kind of
tabular data.
It has no "native" external table format.  What it has is 
a model of what a table looks like, 
a set of java classes for manipulating such tables, 
an extensible framework for table I/O, 
and a number of format-specific I/O handlers for dealing with 
several known table formats.
</p>

<p>This document is a programmers' overview of the abilities of the STIL
libraries, including some tutorial explanation and example code.  
Some parts of it may also be useful background reading for users
of applications built on it.
All the classes and methods are not described in detail here;
that information can be found in the <javadoc class=".">javadocs</javadoc>,
which should be read in conjunction with this document if you are 
actually using these libraries.
Much of the information here is repeated in the javadocs.
The hypertext version of this document links to the relevant places
in the javadocs where appropriate.
</p>

<subsect>
<subhead><title>What is a table?</title></subhead>

<p>In words, STIL's idea of what constitutes a table is something
which has the following:
<ul>
<li>Some per-table metadata (parameters)</li>
<li>A number of columns</li>
<li>Some per-column metadata</li>
<li>A number of rows, each containing one entry per column</li>
</ul>
This model is embodied in the
<javadoc class="uk.ac.starlink.table.StarTable"/> interface,
which is described in <ref id="starTable">the next section</ref>.
It maps quite closely, though not exactly, onto the table model
embodied in the <ref id="votable">VOTable</ref> definition, which
itself owes a certain amount to FITS tables.  This is not coincidence.
</p>

</subsect>
</sect>

<sect id="starTable">
<subhead><title>The StarTable interface</title></subhead>

<p>The most fundamental type in the STIL package is 
<javadoc class="uk.ac.starlink.table.StarTable"
         plaintext="uk.ac.starlink.table.StarTable"/>; 
any time you are using a table, you will use an object which 
implements this interface.
</p>

<subsect>
<subhead><title>Table Metadata</title></subhead>

<p>A few items of the table metadata 
(<javadoc class="uk.ac.starlink.table.StarTable" 
          member="getName()">name</javadoc>,
 <javadoc class="uk.ac.starlink.table.StarTable"
          member="getURL()">URL</javadoc>)
are available directly as values from the <code>StarTable</code> interface.
A general parameter mechanism is provided for storing other items,
for instance user-defined ones.
The <javadoc class="uk.ac.starlink.table.StarTable" member="getParameters()"/>
method returns a list of 
<javadoc class="uk.ac.starlink.table.DescribedValue"/>
objects which contain a value and some metadata describing it
(name, units, UCD).  This list can be read or altered as required.
</p>

<p>The <code>StarTable</code> interface also contains
the methods 
<javadoc class="uk.ac.starlink.table.StarTable" member="getColumnCount()"/>
and <javadoc class="uk.ac.starlink.table.StarTable" member="getRowCount()"/>
to determine the shape of the table.  Note however that for tables
with sequential-only access, it may not be possible to ascertain
the number of rows - in this case <code>getRowCount</code> will return -1.
Random-acess tables (see <ref id="tableData"/>) will always return
a positive row count.
</p>
</subsect>

<subsect id="colMeta">
<subhead><title>Column Metadata</title></subhead>

<p>Each column in a <code>StarTable</code> is assumed to contain the
same sort of thing.  More specifically, for each table column there is 
a <javadoc class="uk.ac.starlink.table.ColumnInfo"/> object 
associated with each column which holds metadata describing 
all the values in that column 
(the value associated with that column for each row in the table).
A <code>ColumnInfo</code> contains information about the
<javadoc class="uk.ac.starlink.table.ValueInfo"
         member="getName()">name</javadoc>,
<javadoc class="uk.ac.starlink.table.ValueInfo"
         member="getUnitString()">units</javadoc>,
<javadoc class="uk.ac.starlink.table.ValueInfo"
         member="getUCD()">UCD</javadoc>,
<javadoc class="uk.ac.starlink.table.ValueInfo"
         member="getContentClass()">class</javadoc>
etc of a column, as well as a mechanism for storing additional
('auxiliary') user-defined metadata.
It also provides methods for rendering the values in the column
under various circumstances.
</p>

<p>The class associated with a column, obtained from the 
<javadoc class="uk.ac.starlink.table.ValueInfo"
         member="getContentClass()"/> method, 
is of particular importance.  Every object in the column described
by that metadata should be an instance of the 
<javadoc class="java.lang.Class" docset="&coredocs;"/> 
<code>getContentClass</code>returns
(or of one of its subtypes), or <code>null</code>.
There is nothing in the tables infrastructure which can enforce
this, but a table which doesn't follow this rule is considered broken,
and application code is within its rights to behave unpredictably 
in this case.
Such a broken table might result from a bug in the I/O handler used
to obtain the table in the first place, or a badly-formed table that
it has read, or a bug in one of the wrapper classes upstream from
the table instance being used.
</p>

<p>This class can be anything 
(with the exception of <code>null</code>
and the primitive types like <code>int.class</code>), 
but most table I/O handlers can only
cope with certain types of value - typically those corresponding to
the java primitive classes (numeric and boolean ones) and 
<javadoc class="java.lang.String" docset="&coredocs;"/>s, so these
are the most important ones to deal with.  The contents of a table
cell must always (as far as the access methods are concerned) be
an <javadoc class="java.lang.Object" docset="&coredocs;"/>,
so primitive values cannot be used directly.
The general rule for primitive-like (numeric or boolean) values
is that a scalar should be represented by the appropriate wrapper class
(<javadoc class="java.lang.Integer" docset="&coredocs;"/>,
 <javadoc class="java.lang.Float" docset="&coredocs;"/>,
 <javadoc class="java.lang.Boolean" docset="&coredocs;"/> etc)
and an array by an array of primitives
(<code>int[]</code>,
 <code>float[]</code>,
 <code>boolean[]</code> etc).
Non-primitive-like objects 
(of which <code>String</code> is the most important example)
should be represented by their own class (for scalars) or an array 
of their own class (for arrays).
Note that it is <em>not</em> recommended to use multidimensional arrays
(i.e. arrays of arrays like <code>int[][]</code>);
a 1-dimensional java array should be used, and information about
the dimensionality should be stored in the <code>ColumnInfo</code>'s 
shape attribute.
Thus to store a 3x2 array of integers, a 6-element array of type
<code>int[]</code> would be used, and the <code>ColumnInfo</code>'s
<javadoc class="uk.ac.starlink.table.ValueInfo" member="getShape()"/> 
method would return a two-element array <code>(3,2)</code>.
</p>

</subsect>

<subsect id="tableData">
<subhead><title>Table Data</title></subhead>

<p>The actual data values in a table are considered to be a sequence
of rows, each containing one value for each of the table's columns.
As explained <ref id="colMeta">above</ref>, each such value 
is an <code>Object</code>, and information about its class
(as well as semantic metadata) is available from the column's
<javadoc class="uk.ac.starlink.table.ColumnInfo"/> object.
</p>

<p><code>StarTable</code>s come in two flavours, 
random-acess and sequential-only;
you can tell which one a given table is by using its 
<javadoc class="uk.ac.starlink.table.StarTable" member="isRandom()"/>
method, and how its data can be accessed is determined by this.
In either case, most of the data access methods are declared to
throw an <javadoc class="java.io.IOException" docset="&coredocs;"/>;
this is because the <code>StarTable</code> object may be obtaining
its data from anywhere, for instance reading it directly off disk
