=== 2lambda123/starjava/topcat/src/docs/docs.dtd
<!ENTITY % paracontent "( #PCDATA
                            | em | strong | code
                            | webref | javadoc | ref
                            | blockquote | blockcode | verbatim
                            | dl | ul | ol
                            | var | label | img
                           )*">

  <!ELEMENT sun ( docinfo?, docbody )>
  <!ELEMENT docinfo ( title?, 
                      authorlist?,
                      softwareversion?,
                      docnumber?,
                      docdate?,
                      contactlist? )>
  <!ELEMENT title ( #PCDATA )>
  <!ELEMENT authorlist ( author* )>
  <!ELEMENT author ( #PCDATA )>
  <!ELEMENT softwareversion ( #PCDATA )>
  <!ELEMENT docnumber ( #PCDATA )>
  <!ELEMENT docdate ( #PCDATA )>
  <!ELEMENT contactlist ( contact* )>
  <!ELEMENT contact %paracontent;>
  <!ELEMENT docbody ( blockcode?, abstract?, sect* )>
  <!ELEMENT abstract ( px* )>
  <!ELEMENT subhead ( title )>
  <!ELEMENT p %paracontent;>
  <!ELEMENT px %paracontent;>
  <!ELEMENT ul ( li* )>
  <!ELEMENT ol ( li* )>
  <!ELEMENT li %paracontent;>
  <!ELEMENT dl ( ( dt, dd? )* )>
  <!ELEMENT dt %paracontent;>
  <!ELEMENT dd ( p* )>
  <!ELEMENT em %paracontent;>
  <!ELEMENT strong %paracontent;>
  <!ELEMENT code %paracontent;>
  <!ELEMENT verbatim %paracontent;>
  <!ELEMENT hidden ( #PCDATA )>
  <!ELEMENT imports ( #PCDATA )>
  <!ELEMENT blockquote %paracontent;>
  <!ELEMENT var %paracontent;>
  <!ELEMENT label %paracontent;>

  <!ELEMENT blockcode ( #PCDATA | imports | hidden )*>
  <!ATTLIST blockcode group NMTOKEN #IMPLIED>

  <!ELEMENT img EMPTY>
  <!ATTLIST img src CDATA #REQUIRED
                alt CDATA #IMPLIED>

  <!ELEMENT ref ( #PCDATA )>
  <!ATTLIST ref id IDREF #REQUIRED
                hypertext CDATA #IMPLIED
                plaintext CDATA #IMPLIED>

  <!ELEMENT webref ( #PCDATA )>
  <!ATTLIST webref url CDATA #REQUIRED
                   hypertext CDATA #IMPLIED
                   plaintext CDATA #IMPLIED>

  <!ELEMENT javadoc ( #PCDATA )>
  <!ATTLIST javadoc class CDATA #REQUIRED
                    member CDATA #IMPLIED
                    docset CDATA #IMPLIED
                    hypertext CDATA #IMPLIED 
                    plaintext CDATA #IMPLIED>

  <!ELEMENT sect ( subhead?, ( p | subsect )* )>
  <!ATTLIST sect id ID #IMPLIED>

  <!ELEMENT subsect ( subhead?, ( p | subsubsect )* )>
  <!ATTLIST subsect id ID #IMPLIED>

  <!ELEMENT subsubsect ( subhead?, ( p | subsubsubsect )* )>
  <!ATTLIST subsubsect id ID #IMPLIED>

  <!ELEMENT subsubsubsect ( subhead?, p* )>
  <!ATTLIST subsubsubsect id ID #IMPLIED>

=== 2lambda123/starjava/topcat/src/docs/sun253.xml
<?xml version='1.0'?>
<!DOCTYPE sun SYSTEM "docs.dtd" [

  <!-- Import entity definitions for icons used by the TOPCAT application. -->
  <!ENTITY % image-defs SYSTEM "image.defs">
  %image-defs;

  <!-- Define illustrations -->
  <!ENTITY figs '../figures/'>
  <!ENTITY FIG.ControlWindow '&figs;ControlWindow.gif'>
  <!ENTITY FIG.ColumnInfoWindow '&figs;ColumnInfoWindow.gif'>
  <!ENTITY FIG.JTable '&figs;JTable.gif'>
  <!ENTITY FIG.ParameterWindow '&figs;ParameterWindow.gif'>
  <!ENTITY FIG.TableViewerWindow '&figs;TableViewerWindow.gif'>
  <!ENTITY FIG.SubsetWindow '&figs;SubsetWindow.gif'>
  <!ENTITY FIG.StatsWindow '&figs;StatsWindow.gif'>
  <!ENTITY FIG.PlotWindow '&figs;PlotWindow.gif'>
  <!ENTITY FIG.LoadQueryWindow '&figs;LoadQueryWindow.gif'>
  <!ENTITY FIG.JFileChooserLoad '&figs;JFileChooserLoad.gif'>
  <!ENTITY FIG.StarTableNodeChooser '&figs;StarTableNodeChooser.gif'>
  <!ENTITY FIG.SQLReadDialog '&figs;SQLReadDialog.gif'>
  <!ENTITY FIG.StarTableSaver '&figs;StarTableSaver.gif'>
  <!ENTITY FIG.JFileChooserSave '&figs;JFileChooserSave.gif'>
  <!ENTITY FIG.SQLWriteDialog '&figs;SQLWriteDialog.gif'>
  <!ENTITY FIG.ConcatWindow '&figs;ConcatWindow.gif'>
  <!ENTITY FIG.MatchWindow '&figs;MatchWindow.gif'>
  <!ENTITY FIG.MatchWindow1 '&figs;MatchWindow1.gif'>
  <!ENTITY FIG.HelpWindow '&figs;HelpWindow.gif'>
  <!ENTITY FIG.SyntheticColumnQueryWindow 
           '&figs;SyntheticColumnQueryWindow.gif'>
  <!ENTITY FIG.SyntheticSubsetQueryWindow 
           '&figs;SyntheticSubsetQueryWindow.gif'>
  <!ENTITY FIG.MethodWindow '&figs;MethodWindow.gif'>

  <!-- Define external URLs. -->
  <!ENTITY URL.VOTABLE "http://www.ivoa.net/Documents/latest/VOT.html">
  <!ENTITY URL.J2SE_JAVADOCS "http://java.sun.com/j2se/1.4/docs/api/">
  <!ENTITY SUN.252 "<webref url='http://www.starlink.ac.uk/stil/sun252/'
                            >SUN/252</webref>">
  <!ENTITY SUN.253 "<webref url='http://www.starlink.ac.uk/topcat/sun253/'
                            >SUN/253</webref>">
]>

<sun>

<docinfo>

<title>TOPCAT - Tool for OPerations on Catalogues And Tables</title>

<authorlist>
<author id="mbt" 
        email="m.b.taylor@bristol.ac.uk"
        webpage="http://www.star.bristol.ac.uk/~mbt/"
        affiliation="Starlink, University of Bristol"
        >Mark Taylor</author>
</authorlist>

<docnumber>253</docnumber>

<docdate>23 April 2004</docdate>

<contactlist>
<contact>TOPCAT web page:
         <webref url="http://www.starlink.ac.uk/topcat/"/></contact>
<contact>Author email:
         <webref url="mailto:m.b.taylor@bristol.ac.uk"
                 >m.b.taylor@bristol.ac.uk</webref></contact>
<contact>Starlink: <webref url="http://www.starlink.ac.uk/"/></contact>
</contactlist>

</docinfo>

<!-- ............................................................... -->
<docbody>

<abstract>
<px>TOPCAT is an interactive graphical viewer and editor for tabular data.
It has been designed for use with astronomical tables such as object 
catalogues, but is not restricted to astronomical applications.
It understands a number of different astronomically important formats,
and more formats can be added.
</px>

<px>It offers a variety of ways to view and analyse the data,
including a browser for the cell data themselves, 
viewers for information about table and column metadata,
and facilities for plotting, calculating statistics and joining tables
using flexible matching algorithms.
Using a powerful and extensible Java-based expression language
new columns can be defined and row subsets selected for separate analysis.
Table data and metadata can be edited and the resulting modified table
can be written out in a wide range of output formats.
</px>

<px>TOPCAT is written in pure Java and available under the 
GNU General Public Licence.  Its underlying table processing facilities
are provided by the Starlink Tables Infrastructure Library.
</px>

</abstract>

<sect id="intro">
<subhead><title>Introduction</title></subhead>

<p>TOPCAT is a graphical program which can view, analyse, combine, edit and
write out tables.  A table is, roughly, anything with columns and rows;
each column contains objects of the same type
(for instance floating point numbers) and each row has an entry for
each of the columns (though some entries might be blank).
A common astronomical example of a table is an object catalogue.
</p>

<p>TOPCAT can read in tables in a number of formats, allow you to
inspect and manipulate them in a number of ways, and if you have
edited them optionally write them out in the modified state for later use,
again in a variety of formats.
Here is a summary of its main capabilities:
<ul>
<li>View/edit table data in a scrollable browser</li>
<li>View/edit table and column metadata</li>
<li>Re-order and hide/reveal columns</li>
<li>Insert 'synthetic' columns defined by algebraic expression</li>
<li>Sort rows on the values in a given column</li>
<li>Define row subsets in various ways</li>
<li>Plot columns against each other, distinguishing different subsets</li>
<li>Calculate statistics on each column for some or all rows</li>
<li>Perform flexible matching of rows in the same or different tables</li>
<li>Concatenate the rows of existing tables to create new ones</li>
<li>Write modified tables out in original or different format</li>
</ul>
</p>

<p>The general idea of the program is quite straightforward.
At any time, it has a list of tables it knows about - these are 
displayed in the <ref id="ControlWindow">Control Window</ref> which 
is the first thing you see when you start up the program.
You can add to the list by <ref id="LoadQueryWindow">loading tables in</ref>,
or by some actions which create new tables from the existing ones.
When you select a table in the list by clicking on it, 
you can see general information
about it in the control window, and you can also open more specialised 
<ref id="views">view windows</ref> which allow you to 
inspect it in more detail or edit it.
Some of the actions you can take, 
such as changing the current 
<ref id="order">Sort Order</ref>,
<ref id="subsets">Row Subset</ref> or
<ref id="columns">Column Set</ref>
change the <ref id="apparent">Apparent Table</ref>, which is a view
of the table used for things such as saving it and performing row matches.
Any changes you make do not modify the tables on disk (or wherever they
came from), but if you want to save the changes you have made,
you can <ref id="StarTableSaver">write</ref> 
the modified table(s) to a new location.
</p>

<p>The main body of this document explains these ideas and capabilities
in more detail; 
<ref id="windows"/> gives a full description of all the windows which
form the application, and
<ref id="tablecopy"/> describes a little command-line utility 
called <label>tablecopy</label> which can copy tables between formats.
While the program is running, this document is available via the
online help system.
</p>

<p>Recent news about the program can be found on the
<webref url="http://www.starlink.ac.uk/topcat/">TOPCAT web page</webref>.
It has been written by the
<webref url="http://www.starlink.ac.uk/">Starlink</webref> project.
The underlying table handling facilities are supplied by
the Starlink Tables Infrastructure Library
(<webref url="http://www.starlink.ac.uk/stil/">STIL</webref>),
which is documented more fully in &SUN.252;.
It is written in pure Java (the current version requires J2SE1.4)
which makes it highly portable (it can run on any machine which has
a suitable Java installation),
and is available under the terms of the 
GNU <webref url="http://www.gnu.org/copyleft/gpl.html"
            >General Public License</webref>.
</p>

</sect>


<sect id="apparent">
<subhead><title>Apparent Table</title></subhead>

<p>The <label>Apparent Table</label> 
is a particular view of a table which can be
influenced by some of the viewing controls.
</p>

<p>When you load a table into TOPCAT it has a number of characteristics
like the number of columns and rows it contains, the order of the rows
that make up the data, the data and metadata themselves, and so on.
While manipulating it you can modify the way that the table appears
to the program, by changing or adding data or metadata, 
or changing the order or selection of columns or rows that are visible.
For each table the "apparent table" is a table which corresponds to
the current state of the table according to the changes that you have made.
</p>

<p>In detail, the apparent table consists of the table as it was originally
imported into the program plus any of the following changes that you
have made:
<ul>
<li>Changes to the current 
    <ref id="columns" plaintextref="yes">Column Set</ref> caused
    by adding, hiding or moving columns</li>
<li>Changes to the current 
    <ref id="order" plaintextref="yes">Row Order</ref> caused by 
    doing a sort</li>
<li>Selection of rows changed by changing the current
    <ref id="subsets" plaintextref="yes">Row Subset</ref></li>
<li>Changes to cell data by editing cells in the 
    <ref id="TableViewerWindow">Data window</ref></li>
<li>Changes to table metadata by editing cells in the 
    <ref id="ParameterWindow">Parameter window</ref></li>
<li>Changes to column metadata by editing cells in the 
    <ref id="ColumnInfoWindow">Columns window</ref></li>
</ul>
</p>

<p>The apparent table is used in the following contexts:
<dl>

<dt>Data Window</dt>
<dd><p>The <ref id="TableViewerWindow">Data window</ref>
    always shows the apparent table, so if you are in doubt about what
    form a table will get exported in, you can see what it looks like there.
    </p></dd>

<dt>Exports</dt>
<dd><p>When you save a table, or export it by dragging it off the
    Table List panel in the <ref id="ControlWindow">Control Window</ref>,
    or create a duplicate table,
    it is the apparent table which is copied.
    So for instance if you define a subset containing only the first
    ten rows of a table
